# Generated by Django 4.1.3 on 2024-06-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2024-06-04', verbose_name='Fecha de Cambio del Logotipo'),
        ),
    ]
