# Generated by Django 4.1.3 on 2024-06-03 14:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import xavi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accion_control_etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=65, unique=True, verbose_name='nombre*')),
                ('centro_costo', models.CharField(blank=True, max_length=10, null=True, verbose_name='centro de costo*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='autor_sosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre*')),
                ('siglas', models.CharField(max_length=6, verbose_name='siglas*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, verbose_name='nombre*')),
                ('nombre', models.CharField(max_length=65, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='control_etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='estado_acuerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, null=True, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='estado_entradas_proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='estado_indicador_objetivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='estado_proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='estado_proyecto_dgca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='estado_software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='etapa_proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=3, unique=True, verbose_name='valor*')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='financiamiento_proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=20, null=True, verbose_name='valor financiamiento*')),
                ('valor_real', models.CharField(blank=True, max_length=20, null=True, verbose_name='valor real financiamiento*')),
                ('ingreso', models.CharField(blank=True, max_length=20, null=True, verbose_name='ingreso financiamiento*')),
                ('ingreso_real', models.CharField(blank=True, max_length=20, null=True, verbose_name='ingreso real financiamiento*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='formato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
        ),
        migrations.CreateModel(
            name='fuente_financiamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
        ),
        migrations.CreateModel(
            name='linea_tematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55, unique=True, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=10, verbose_name='número*')),
                ('nombre', models.CharField(max_length=300, verbose_name='nombre*')),
                ('fecha_definicion', models.DateField(verbose_name='fecha de definición*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre*')),
                ('orden', models.CharField(blank=True, max_length=3, null=True, verbose_name='orden*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=10, null=True, verbose_name='número*')),
                ('codigo', models.CharField(max_length=10, null=True, verbose_name='código*')),
                ('nombre_proyecto', models.CharField(max_length=250, null=True, verbose_name='nombre de proyecto*')),
                ('creado', models.DateField(default=datetime.datetime.now, verbose_name='fecha de creado en base de datos*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xavi.estado_proyecto', verbose_name='estado*')),
                ('formato', models.ManyToManyField(related_name='proyecto', to='xavi.formato', verbose_name='formato')),
            ],
        ),
        migrations.CreateModel(
            name='registro_aprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(max_length=20, null=True, verbose_name='contrato*')),
                ('fecha_inicio', models.DateField(default=datetime.datetime.now, verbose_name='fecha de inicio*')),
                ('fecha_terminacion', models.DateField(blank=True, null=True, verbose_name='fecha de fin')),
                ('ingreso_mlc', models.CharField(blank=True, max_length=20, null=True, verbose_name='ingreso en mlc*')),
                ('ingreso_cup', models.CharField(blank=True, max_length=20, null=True, verbose_name='ingreso en cup*')),
                ('fecha_aprobacion', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='fecha de aprobación Consejo Editorial')),
                ('aprobacion_consejo', models.CharField(blank=True, max_length=25, null=True, verbose_name='aprobación Consejo Editorial')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xavi.area', verbose_name='centro de costo*')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xavi.cliente', verbose_name='cliente*')),
            ],
        ),
        migrations.CreateModel(
            name='registro_reinicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default='<built-in method now of type object at 0x55d96dd28860>', verbose_name='fecha de inicio del reinicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha de fin del reinicio')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre*')),
                ('siglas', models.CharField(max_length=25, verbose_name='siglas*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='trabajador_registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee', verbose_name='trabajador*')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xavi.registro_aprobacion', verbose_name='registro de aprobación*')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.position', verbose_name='rol*')),
            ],
        ),
        migrations.CreateModel(
            name='trabajador_proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee', verbose_name='trabajador*')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xavi.proyecto', verbose_name='proyecto*')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.position', verbose_name='rol*')),
            ],
        ),
        migrations.CreateModel(
            name='trabajador_etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='fecha de inicio*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('accion_control_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xavi.accion_control_etapa', verbose_name='accion en el control de etapa*')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee', verbose_name='trabajador*')),
                ('estado_software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xavi.estado_software', verbose_name='estado de software*')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xavi.control_etapa', verbose_name='control de etapa*')),
            ],
        ),
        migrations.CreateModel(
            name='trabajador_consecutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.employee', verbose_name='trabajador*')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.position', verbose_name='rol*')),
            ],
        ),
        migrations.CreateModel(
            name='subclasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siglas', models.CharField(max_length=6, verbose_name='siglas*')),
                ('nombre', models.CharField(max_length=80, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclasificacion', to='xavi.clasificacion', verbose_name='clasificación*')),
            ],
        ),
        migrations.CreateModel(
            name='sosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_salva', models.CharField(max_length=10, verbose_name='número*')),
                ('fecha', models.DateField(blank=True, default='2024-06-03', null=True, verbose_name='fecha de entrada*')),
                ('ubicacion_salva', models.CharField(blank=True, max_length=10, null=True, verbose_name='ubicación')),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True, verbose_name='observaciones')),
                ('archivo', models.CharField(blank=True, max_length=150, null=True, verbose_name='ruta del archivo')),
                ('colectivo', models.BooleanField(default=False, verbose_name='colectivo de autores')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('autor', models.ManyToManyField(blank=True, null=True, to='xavi.autor_sosi', verbose_name='autor')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.employee', verbose_name='trabajador que entrega*')),
                ('idioma', models.ManyToManyField(blank=True, to='xavi.idioma', verbose_name='Idioma*')),
                ('proyecto', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sosi', to='xavi.proyecto', verbose_name='proyecto*')),
                ('recibe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recibe', to='base.employee', verbose_name='trabajador que recibe*')),
            ],
        ),
        migrations.CreateModel(
            name='representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xavi.cliente', verbose_name='cliente*')),
            ],
        ),
        migrations.CreateModel(
            name='registro_terminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendaciones', models.CharField(blank=True, max_length=250, null=True, verbose_name='recomendaciones control de calidad')),
                ('fecha_revision', models.DateField(default=datetime.datetime.now, verbose_name='fecha de revisión*')),
                ('fecha_verificacion', models.DateField(default=datetime.datetime.now, verbose_name='fecha de verificación*')),
                ('ingreso_mlc', models.CharField(blank=True, max_length=20, null=True, verbose_name='ingreso en mlc*')),
                ('ingreso_cup', models.CharField(blank=True, max_length=20, null=True, verbose_name='ingreso en cup*')),
                ('no_ficha_tecnica', models.CharField(blank=True, max_length=5, null=True, verbose_name='número ficha técnica')),
                ('fecha_ficha_tecnica', models.DateField(default=datetime.datetime.now, verbose_name='fecha de ficha técnica*')),
                ('fecha_sosi', models.DateField(default=datetime.datetime.now, verbose_name='fecha de sosi*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='registro_terminacion_cliente', to='xavi.cliente', verbose_name='verificado por*')),
                ('financiamiento', models.ManyToManyField(blank=True, through='xavi.financiamiento_proyecto', to='xavi.fuente_financiamiento', verbose_name='financiamiento*')),
                ('no_sosi', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='registro_terminacion', to='xavi.sosi', verbose_name='sosi*')),
                ('proyecto', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proyecto_registro_terminacion', to='xavi.proyecto', verbose_name='registro de terminación*')),
                ('recibida_por_sosi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='registro_terminacion_recibida_sosi', to='base.employee', verbose_name='recibida por (sosi)*')),
                ('recibido_por_ficha_tecnica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='registro_terminacion_recibido_ficha_tecnica', to='base.employee', verbose_name='recibido por (ficha técnica)*')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='registro_terminacion_revisado', to='base.employee', verbose_name='revisado por*')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='registro_terminacion_verificado', to='base.employee', verbose_name='verificado por*')),
            ],
        ),
        migrations.CreateModel(
            name='registro_interrupcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='fecha de interrupción*')),
                ('motivo', models.CharField(blank=True, max_length=250, null=True, verbose_name='motivo')),
                ('aprobado_por', models.CharField(blank=True, max_length=130, null=True, verbose_name='aprobado por')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('financiamiento', models.ManyToManyField(blank=True, through='xavi.financiamiento_proyecto', to='xavi.fuente_financiamiento', verbose_name='financiamiento*')),
                ('propuesto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.employee', verbose_name='propuesto por*')),
                ('proyecto', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proyecto_registro_interrupcion', to='xavi.proyecto', verbose_name='registro de interrupción*')),
            ],
        ),
        migrations.CreateModel(
            name='registro_extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True, verbose_name='observaciones')),
                ('fecha_inicio', models.DateField(default=datetime.datetime.now, verbose_name='fecha de inicio*')),
                ('fecha_fin', models.DateField(default=datetime.datetime.now, verbose_name='fecha de fin*')),
                ('fecha_aprobacion', models.DateField(default=datetime.datetime.now, verbose_name='fecha de aprobación*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xavi.area', verbose_name='centro de costo*')),
                ('jefe_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.employee', verbose_name='jefe de proyecto*')),
                ('proyecto', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proyecto_registro_extension', to='xavi.proyecto', verbose_name='registro de extensión*')),
                ('tipo_extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xavi.tipo_extension', verbose_name='tipo de extensión*')),
            ],
        ),
        migrations.AddField(
            model_name='registro_aprobacion',
            name='employee',
            field=models.ManyToManyField(through='xavi.trabajador_registro', to='base.employee', verbose_name='rol en el registro*'),
        ),
        migrations.AddField(
            model_name='registro_aprobacion',
            name='financiamiento',
            field=models.ManyToManyField(blank=True, null=True, through='xavi.financiamiento_proyecto', to='xavi.fuente_financiamiento', verbose_name='financiamiento*'),
        ),
        migrations.AddField(
            model_name='registro_aprobacion',
            name='linea_tematica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xavi.linea_tematica', verbose_name='línea temática'),
        ),
        migrations.AddField(
            model_name='registro_aprobacion',
            name='registro_reinicio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xavi.registro_reinicio', verbose_name='reinicio*'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='registro_aprobacion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proyecto', to='xavi.registro_aprobacion', verbose_name='registro de aprobación*'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='subclasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proyectos', to='xavi.subclasificacion', verbose_name='subclasificación*'),
        ),
        migrations.CreateModel(
            name='premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre*')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='descripcion')),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='fecha*')),
                ('archivo', models.FileField(null=True, upload_to=xavi.models.premio.ruta, verbose_name='planilla de la Reserva')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('entidad', models.ForeignKey(on_delete=models.SET('CITMATEL'), to='base.entity', verbose_name='entidad*')),
            ],
        ),
        migrations.CreateModel(
            name='plan_ingreso_aprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=15, null=True, verbose_name='valor financiamiento*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('fuente_financiamiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xavi.fuente_financiamiento', verbose_name='fuente de financiamiento*')),
                ('registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xavi.registro_aprobacion', verbose_name='registro de aprobación*')),
                ('registro_terminacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xavi.registro_terminacion', verbose_name='registro de terminación*')),
                ('tipo_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xavi.tipo_moneda', verbose_name='rol*')),
            ],
        ),
        migrations.CreateModel(
            name='indicador_objetivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=10, verbose_name='número*')),
                ('nombre', models.CharField(max_length=250, null=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='xavi.objetivo', verbose_name='objetivo')),
            ],
        ),
        migrations.AddField(
            model_name='financiamiento_proyecto',
            name='fuente_financiamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xavi.fuente_financiamiento', verbose_name='fuente de financiamiento*'),
        ),
        migrations.AddField(
            model_name='financiamiento_proyecto',
            name='registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xavi.registro_aprobacion', verbose_name='registro de aprobación*'),
        ),
        migrations.AddField(
            model_name='financiamiento_proyecto',
            name='registro_interrupcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xavi.registro_interrupcion', verbose_name='registro de interrupcion*'),
        ),
        migrations.AddField(
            model_name='financiamiento_proyecto',
            name='registro_terminacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xavi.registro_terminacion', verbose_name='registro de terminación*'),
        ),
        migrations.AddField(
            model_name='financiamiento_proyecto',
            name='tipo_moneda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xavi.tipo_moneda', verbose_name='tipo de moneda*'),
        ),
        migrations.CreateModel(
            name='evaluacion_trimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_trimestral', to='xavi.evaluacion', verbose_name='valor*')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_trimestral', to='xavi.objetivo', verbose_name='objetivo*')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_trimestral', to='xavi.periodo', verbose_name='periodo*')),
            ],
        ),
        migrations.AddField(
            model_name='estado_proyecto',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='xavi.etapa_proyecto', verbose_name='Etapa de proyecto*'),
        ),
        migrations.CreateModel(
            name='entrada_proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=10, verbose_name='número*')),
                ('fecha_entrada', models.DateField(default=datetime.datetime.now, verbose_name='fecha*')),
                ('fecha_salida', models.DateField(null=True, verbose_name='Fecha de salida')),
                ('dictamen', models.FileField(blank=True, null=True, upload_to='entradas_proyectos/', verbose_name='informe apertura')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo*')),
                ('entregado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee', verbose_name='Trabajador que entrega')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrada_proyecto', to='xavi.estado_proyecto_dgca', verbose_name='Estado entrada proyecto')),
                ('formato', models.ManyToManyField(to='xavi.formato', verbose_name='Formato*')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='xavi.proyecto', verbose_name='Proyecto*')),
            ],
        ),
        migrations.AddField(
            model_name='control_etapa',
            name='employee',
            field=models.ManyToManyField(through='xavi.trabajador_etapa', to='base.employee', verbose_name='rol en el registro*'),
        ),
        migrations.AddField(
            model_name='control_etapa',
            name='proyecto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proyecto_control_etapa', to='xavi.proyecto', verbose_name='registro de extensión*'),
        ),
        migrations.CreateModel(
            name='calidad_proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xavi.proyecto', verbose_name='proyecto*')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee', verbose_name='rol en control de calidad*')),
            ],
        ),
        migrations.CreateModel(
            name='acuerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=6, null=True, unique=True, verbose_name='Número de acuerdo*')),
                ('nombre', models.CharField(max_length=125, null=True, verbose_name='Nombre del acuerdo*')),
                ('fecha', models.DateField(verbose_name='fecha*')),
                ('fecha_limite', models.DateField(null=True, verbose_name='fecha límite para cumplir')),
                ('fecha_cumplimiento', models.DateField(null=True, verbose_name='fecha de cumplimiento')),
                ('observaciones', models.TextField(null=True, verbose_name='observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('employee', models.ManyToManyField(to='base.employee', verbose_name='responsable*')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xavi.estado_acuerdo', verbose_name='estado de acuerdo*')),
            ],
        ),
        migrations.CreateModel(
            name='accion_indicador_objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=10, null=True, verbose_name='número*')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, verbose_name='codigo*')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo*')),
                ('indicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accion', to='xavi.indicador_objetivos', verbose_name='indicador*')),
            ],
        ),
        migrations.CreateModel(
            name='descripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='descripcion*')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo*')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('area_principal', models.BooleanField(default=False, verbose_name='Área principal*')),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descripcion', to='xavi.accion_indicador_objetivo', verbose_name='acción*')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descripcion', to='xavi.area', verbose_name='área*')),
            ],
            options={
                'unique_together': {('accion', 'area')},
            },
        ),
    ]
