# Generated by Django 4.1.3 on 2024-06-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xavi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accion_indicador_objetivo',
            name='nombre',
            field=models.CharField(max_length=250, verbose_name='nombre*'),
        ),
        migrations.AlterField(
            model_name='registro_reinicio',
            name='fecha_inicio',
            field=models.DateField(default='<built-in method now of type object at 0x56466255d860>', verbose_name='fecha de inicio del reinicio'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='fecha',
            field=models.DateField(blank=True, default='2024-06-04', null=True, verbose_name='fecha de entrada*'),
        ),
    ]
