# Generated by Django 4.1.3 on 2024-06-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xavi', '0002_alter_accion_indicador_objetivo_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea_tematica',
            name='nombre',
            field=models.CharField(max_length=55, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='registro_reinicio',
            name='fecha_inicio',
            field=models.DateField(default='<built-in method now of type object at 0x555dfd63e860>', verbose_name='fecha de inicio del reinicio'),
        ),
    ]
