# Generated by Django 4.1.3 on 2024-06-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xavi', '0003_alter_linea_tematica_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdo',
            name='nombre',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Nombre del acuerdo*'),
        ),
        migrations.AlterField(
            model_name='acuerdo',
            name='numero',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Número de acuerdo*'),
        ),
        migrations.AlterField(
            model_name='registro_reinicio',
            name='fecha_inicio',
            field=models.DateField(default='<built-in method now of type object at 0x563348208860>', verbose_name='fecha de inicio del reinicio'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='fecha',
            field=models.DateField(blank=True, default='2024-06-06', null=True, verbose_name='fecha de entrada*'),
        ),
    ]
