# Generated by Django 4.2.8 on 2024-06-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xavi', '0005_alter_registro_reinicio_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_reinicio',
            name='fecha_inicio',
            field=models.DateField(default='<built-in method now of type object at 0x00007FFF5653B650>', verbose_name='fecha de inicio del reinicio'),
        ),
    ]
